DELETE FROM MREG_CLIENT_DETAILS
WHERE CLIENT_ID IN (
    SELECT CLIENT_ID
    FROM MREG_CLIENT
    WHERE CLIENT_NAME LIKE 'TEST%'
);
DELETE FROM MD_ADDRESS
WHERE CLIENT_ID IN (
    SELECT CLIENT_ID FROM MREG_CLIENT WHERE CLIENT_NAME LIKE 'TEST%'
);


DELETE FROM MREG_CLIENT
WHERE CLIENT_NAME LIKE 'TEST%';